language: node_js
node_js: lts/*
sudo: required
dist: precise
install:
  - npm cache verify
  - npm install
script:
  - npm test
  - npm run build
services:
  - docker
after_succes:
  - docker build -t javierseixas/file-storage-ui-client:latest .
cache:
  directories:
    - $HOME/.npm
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master