language: node_js
node_js: lts/*
sudo: required
dist: trusty
services:
  - docker
install:
  - npm cache verify
  - npm install
script:
  - npm test
  - npm run build
  - docker -v
before_deploy:
  - docker build -t javierseixas/file-storage-ui-client:latest .
cache:
  directories:
    - $HOME/.npm
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master